
server:
  port: 8081
  servlet:
    context-path: /hotel

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_db
    username: root
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  prefix: api/v1

