server:
  port: 8080
  servlet:
    context-path: /shopapp

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/orderfood
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
api:
  prefix: api/v1